/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

const Trade = IDL.Record({
  id: IDL.Text,
  name: IDL.Text,
  status: IDL.Text,
  createdAt: IDL.Int,
});

const Department = IDL.Record({
  id: IDL.Text,
  name: IDL.Text,
  status: IDL.Text,
  createdAt: IDL.Int,
});

const Site = IDL.Record({
  id: IDL.Text,
  name: IDL.Text,
  status: IDL.Text,
  lat: IDL.Float64,
  lng: IDL.Float64,
  radiusMeters: IDL.Float64,
  createdAt: IDL.Int,
});

const Employee = IDL.Record({
  id: IDL.Text,
  employeeId: IDL.Text,
  name: IDL.Text,
  mobile: IDL.Text,
  site: IDL.Text,
  tradeId: IDL.Text,
  departmentId: IDL.Text,
  status: IDL.Text,
  salaryMode: IDL.Text,
  cityType: IDL.Text,
  basicSalary: IDL.Float64,
  hra: IDL.Float64,
  conveyance: IDL.Float64,
  specialAllowance: IDL.Float64,
  otherAllowance: IDL.Float64,
  otRate: IDL.Float64,
  pfApplicable: IDL.Bool,
  esiApplicable: IDL.Bool,
  createdAt: IDL.Int,
});

const AttendanceRecord = IDL.Record({
  id: IDL.Text,
  employeeId: IDL.Text,
  date: IDL.Text,
  status: IDL.Text,
  otHours: IDL.Float64,
  punchIn: IDL.Text,
  punchOut: IDL.Text,
  lat: IDL.Float64,
  lng: IDL.Float64,
  isFlagged: IDL.Bool,
  flagReason: IDL.Text,
  isRegularized: IDL.Bool,
  regularizationReason: IDL.Text,
  changedBy: IDL.Text,
  updatedAt: IDL.Int,
  createdAt: IDL.Int,
});

const PayrollRecord = IDL.Record({
  id: IDL.Text,
  employeeId: IDL.Text,
  month: IDL.Nat,
  year: IDL.Nat,
  basicSalary: IDL.Float64,
  hra: IDL.Float64,
  conveyance: IDL.Float64,
  specialAllowance: IDL.Float64,
  otherAllowance: IDL.Float64,
  otAmount: IDL.Float64,
  grossPay: IDL.Float64,
  pfDeduction: IDL.Float64,
  esiDeduction: IDL.Float64,
  netPay: IDL.Float64,
  generatedAt: IDL.Int,
});

const PayrollSummary = IDL.Record({
  totalEmployees: IDL.Nat,
  totalGross: IDL.Float64,
  totalDeductions: IDL.Float64,
  totalNetPay: IDL.Float64,
});

const AuditLog = IDL.Record({
  id: IDL.Text,
  entityType: IDL.Text,
  entityId: IDL.Text,
  oldValue: IDL.Text,
  newValue: IDL.Text,
  changedBy: IDL.Text,
  timestamp: IDL.Int,
  reason: IDL.Text,
});

const Advance = IDL.Record({
  id: IDL.Text,
  employeeId: IDL.Text,
  amount: IDL.Float64,
  date: IDL.Text,
  site: IDL.Text,
  createdAt: IDL.Int,
});

const Supervisor = IDL.Record({
  phone: IDL.Text,
  name: IDL.Text,
  siteId: IDL.Text,
  pin: IDL.Text,
  active: IDL.Bool,
});

export const idlService = IDL.Service({
  isCallerAdmin: IDL.Func([], [IDL.Bool], []),

  getTrades: IDL.Func([], [IDL.Record({ trades: IDL.Vec(Trade), activeTrades: IDL.Vec(Trade) })], ['query']),
  createTrade: IDL.Func([IDL.Text], [IDL.Bool], []),
  updateTrade: IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),

  getDepartments: IDL.Func([], [IDL.Record({ departments: IDL.Vec(Department), activeDepartments: IDL.Vec(Department) })], ['query']),
  createDepartment: IDL.Func([IDL.Text], [IDL.Bool], []),
  updateDepartment: IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),

  getSites: IDL.Func([], [IDL.Record({ sites: IDL.Vec(Site), activeSites: IDL.Vec(Site) })], ['query']),
  createSite: IDL.Func([IDL.Text, IDL.Float64, IDL.Float64, IDL.Float64], [IDL.Bool], []),
  updateSite: IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Float64, IDL.Float64], [IDL.Bool], []),

  getEmployees: IDL.Func([], [IDL.Record({ allEmployees: IDL.Vec(Employee), activeEmployees: IDL.Vec(Employee) })], ['query']),
  createEmployee: IDL.Func([Employee], [IDL.Bool], []),
  updateEmployee: IDL.Func([IDL.Text, Employee], [IDL.Bool], []),

  markAttendance: IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Text, IDL.Text, IDL.Float64, IDL.Float64, IDL.Text], [IDL.Bool], []),
  updateAttendanceOT: IDL.Func([IDL.Text, IDL.Text, IDL.Float64, IDL.Text], [IDL.Bool], []),
  bulkMarkAttendance: IDL.Func(
    [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text, IDL.Text, IDL.Float64)), IDL.Text],
    [IDL.Record({ successCount: IDL.Nat, skippedCount: IDL.Nat, errors: IDL.Vec(IDL.Text) })],
    []
  ),
  getAttendanceByMonth: IDL.Func([IDL.Text, IDL.Text], [IDL.Vec(AttendanceRecord)], ['query']),
  getAllAttendance: IDL.Func([], [IDL.Vec(AttendanceRecord)], ['query']),
  regularizeAttendance: IDL.Func([IDL.Text, IDL.Text, IDL.Float64, IDL.Text, IDL.Text], [IDL.Bool], []),
  flagAttendance: IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),

  addAdvance: IDL.Func([IDL.Text, IDL.Float64, IDL.Text, IDL.Text], [IDL.Bool], []),
  getAdvancesByEmployee: IDL.Func([IDL.Text], [IDL.Vec(Advance)], ['query']),

  getAuditLogs: IDL.Func([], [IDL.Vec(AuditLog)], ['query']),

  generatePayroll: IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [IDL.Record({ generatedCount: IDL.Nat })], []),
  overwritePayroll: IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [IDL.Record({ generatedCount: IDL.Nat })], []),
  getPayrollByMonth: IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(PayrollRecord)], ['query']),
  getPayrollSummary: IDL.Func([IDL.Nat, IDL.Nat], [PayrollSummary], ['query']),

  getSupervisors: IDL.Func([], [IDL.Vec(Supervisor)], ['query']),
  addSupervisor: IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
  removeSupervisor: IDL.Func([IDL.Text], [IDL.Bool], []),
  verifySupervisorPin: IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Trade = IDL.Record({
    id: IDL.Text,
    name: IDL.Text,
    status: IDL.Text,
    createdAt: IDL.Int,
  });

  const Department = IDL.Record({
    id: IDL.Text,
    name: IDL.Text,
    status: IDL.Text,
    createdAt: IDL.Int,
  });

  const Site = IDL.Record({
    id: IDL.Text,
    name: IDL.Text,
    status: IDL.Text,
    lat: IDL.Float64,
    lng: IDL.Float64,
    radiusMeters: IDL.Float64,
    createdAt: IDL.Int,
  });

  const Employee = IDL.Record({
    id: IDL.Text,
    employeeId: IDL.Text,
    name: IDL.Text,
    mobile: IDL.Text,
    site: IDL.Text,
    tradeId: IDL.Text,
    departmentId: IDL.Text,
    status: IDL.Text,
    salaryMode: IDL.Text,
    cityType: IDL.Text,
    basicSalary: IDL.Float64,
    hra: IDL.Float64,
    conveyance: IDL.Float64,
    specialAllowance: IDL.Float64,
    otherAllowance: IDL.Float64,
    otRate: IDL.Float64,
    pfApplicable: IDL.Bool,
    esiApplicable: IDL.Bool,
    createdAt: IDL.Int,
  });

  const AttendanceRecord = IDL.Record({
    id: IDL.Text,
    employeeId: IDL.Text,
    date: IDL.Text,
    status: IDL.Text,
    otHours: IDL.Float64,
    punchIn: IDL.Text,
    punchOut: IDL.Text,
    lat: IDL.Float64,
    lng: IDL.Float64,
    isFlagged: IDL.Bool,
    flagReason: IDL.Text,
    isRegularized: IDL.Bool,
    regularizationReason: IDL.Text,
    changedBy: IDL.Text,
    updatedAt: IDL.Int,
    createdAt: IDL.Int,
  });

  const PayrollRecord = IDL.Record({
    id: IDL.Text,
    employeeId: IDL.Text,
    month: IDL.Nat,
    year: IDL.Nat,
    basicSalary: IDL.Float64,
    hra: IDL.Float64,
    conveyance: IDL.Float64,
    specialAllowance: IDL.Float64,
    otherAllowance: IDL.Float64,
    otAmount: IDL.Float64,
    grossPay: IDL.Float64,
    pfDeduction: IDL.Float64,
    esiDeduction: IDL.Float64,
    netPay: IDL.Float64,
    generatedAt: IDL.Int,
  });

  const PayrollSummary = IDL.Record({
    totalEmployees: IDL.Nat,
    totalGross: IDL.Float64,
    totalDeductions: IDL.Float64,
    totalNetPay: IDL.Float64,
  });

  const AuditLog = IDL.Record({
    id: IDL.Text,
    entityType: IDL.Text,
    entityId: IDL.Text,
    oldValue: IDL.Text,
    newValue: IDL.Text,
    changedBy: IDL.Text,
    timestamp: IDL.Int,
    reason: IDL.Text,
  });

  const Advance = IDL.Record({
    id: IDL.Text,
    employeeId: IDL.Text,
    amount: IDL.Float64,
    date: IDL.Text,
    site: IDL.Text,
    createdAt: IDL.Int,
  });

  const Supervisor = IDL.Record({
    phone: IDL.Text,
    name: IDL.Text,
    siteId: IDL.Text,
    pin: IDL.Text,
    active: IDL.Bool,
  });

  return IDL.Service({
    isCallerAdmin: IDL.Func([], [IDL.Bool], []),

    getTrades: IDL.Func([], [IDL.Record({ trades: IDL.Vec(Trade), activeTrades: IDL.Vec(Trade) })], ['query']),
    createTrade: IDL.Func([IDL.Text], [IDL.Bool], []),
    updateTrade: IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),

    getDepartments: IDL.Func([], [IDL.Record({ departments: IDL.Vec(Department), activeDepartments: IDL.Vec(Department) })], ['query']),
    createDepartment: IDL.Func([IDL.Text], [IDL.Bool], []),
    updateDepartment: IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),

    getSites: IDL.Func([], [IDL.Record({ sites: IDL.Vec(Site), activeSites: IDL.Vec(Site) })], ['query']),
    createSite: IDL.Func([IDL.Text, IDL.Float64, IDL.Float64, IDL.Float64], [IDL.Bool], []),
    updateSite: IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Float64, IDL.Float64], [IDL.Bool], []),

    getEmployees: IDL.Func([], [IDL.Record({ allEmployees: IDL.Vec(Employee), activeEmployees: IDL.Vec(Employee) })], ['query']),
    createEmployee: IDL.Func([Employee], [IDL.Bool], []),
    updateEmployee: IDL.Func([IDL.Text, Employee], [IDL.Bool], []),

    markAttendance: IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Text, IDL.Text, IDL.Float64, IDL.Float64, IDL.Text], [IDL.Bool], []),
    updateAttendanceOT: IDL.Func([IDL.Text, IDL.Text, IDL.Float64, IDL.Text], [IDL.Bool], []),
    bulkMarkAttendance: IDL.Func(
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text, IDL.Text, IDL.Float64)), IDL.Text],
      [IDL.Record({ successCount: IDL.Nat, skippedCount: IDL.Nat, errors: IDL.Vec(IDL.Text) })],
      []
    ),
    getAttendanceByMonth: IDL.Func([IDL.Text, IDL.Text], [IDL.Vec(AttendanceRecord)], ['query']),
    getAllAttendance: IDL.Func([], [IDL.Vec(AttendanceRecord)], ['query']),
    regularizeAttendance: IDL.Func([IDL.Text, IDL.Text, IDL.Float64, IDL.Text, IDL.Text], [IDL.Bool], []),
    flagAttendance: IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),

    addAdvance: IDL.Func([IDL.Text, IDL.Float64, IDL.Text, IDL.Text], [IDL.Bool], []),
    getAdvancesByEmployee: IDL.Func([IDL.Text], [IDL.Vec(Advance)], ['query']),

    getAuditLogs: IDL.Func([], [IDL.Vec(AuditLog)], ['query']),

    generatePayroll: IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [IDL.Record({ generatedCount: IDL.Nat })], []),
    overwritePayroll: IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [IDL.Record({ generatedCount: IDL.Nat })], []),
    getPayrollByMonth: IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(PayrollRecord)], ['query']),
    getPayrollSummary: IDL.Func([IDL.Nat, IDL.Nat], [PayrollSummary], ['query']),

    getSupervisors: IDL.Func([], [IDL.Vec(Supervisor)], ['query']),
    addSupervisor: IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
    removeSupervisor: IDL.Func([IDL.Text], [IDL.Bool], []),
    verifySupervisorPin: IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };
